### ISSUE TITLE
arguments in motif search

### ISSUE THREAD

**Issue by anna-panchenko** [neksa/mutagene#32]
Currently thresholds "-t" are not included in "advanced arguments". We should also include thresholds on individual p-values.

I don’t think it is clear what “TN”, “NA”… mean;
I would call these options “transcribed”,”non-transcribed”, “any” or “both” (“TN”?)

--save-motif-matches
“save mutations in matching motifs to a BED file”

**Comment by neksa** [comment]
I can see -t in advanced arguments (version 0.9.0):

`  --threshold THRESHOLD, -t THRESHOLD
                        Significance threshold for qvalues, default value=0.05`


TN  is essentially two consecutive, independent tests:  first T, then N.
A means we consider all mutations in one test. I will simplify the help usage message.  It's either T or N or A

Changed --save-motif-matches  help
