### ISSUE TITLE
web server and package

### ISSUE THREAD

**Issue by anna-panchenko** [neksa/mutagene#39]
the webserver and package produce different results:

(env_mutagene) Annas-MBP:mutagene panch$ mutagene signature -i TSVC_variants_IonXpress_019_\(BCMDS-116\).vcf -g hg38 -f VCF -s 10 -U
sample  signature       exposure        mutations
VCF        2              0.0535   3
VCF        3              0.1164   7
VCF        4              0.1134   7
VCF        5              0.1244   7
VCF        6              0.3912   23
VCF        7              0.1603   9
VCF        8              0.0109   1
VCF        9              0.0274   2
(env_mutagene) Annas-MBP:mutagene panch$ mutagene signature -i TSVC_variants_IonXpress_019_\(BCMDS-116\).vcf -g hg38 -f VCF -s 10
sample  signature       exposure        mutations
VCF        1              0.0144   1
VCF        3              0.1123   7
VCF        4              0.0514   3
VCF        5              0.1074   6
VCF        6              0.1604   9
VCF        7              0.0341   2
VCF        9              0.0328   2

**Comment by neksa** [comment]
Investigated. The reason is different input signatures - they differ in rounding/mantissa. Also need to specify -m compat for reproducibility.
