### ISSUE TITLE
non-informative error message

### ISSUE THREAD

**Issue by anna-panchenko** [neksa/mutagene#54]
Specifying the wrong genome assembly returns an error about the maf format:
(env_mutagene) Annas-MacBook-Pro:mutagene panch$ mutagene -v rank -g hg18 -i TCGA.UCEC.mutect.somatic.maf
WARNING Parsing MAF failed. Check that the input file is in MAF format or specify a different format using option -f
FileNotFoundError(2, 'No such file or directory')

**Comment by neksa** [comment]
Confirmed. If hg18.2bit is not found the message is misleading.

**Comment by shandy79** [comment]
I'll look into providing a more informative error message.

**Comment by shandy79** [comment]
Closed w/PR 57
